### PR TITLE
The translation of Simplified Chinese has been fully completed （简体中文的翻译已经全部完成）

### PR DESCRIPTION
**Pull request by taskmgrTZT**
English：
The translation of Simplified Chinese has been completed to line 850 (<data name="N_Collections. Content" xml: space="preserve">) I will complete the rest of the work tomorrow and the day after tomorrow

简体中文：
简体中文的翻译已经翻译到第850行（<data name="N_Collections.Content" xml:space="preserve">） 其余的部分我会在明后天完成

### CODE REVIEW

**Comment by taskmgrTZT** [comment]
English：
All translations within the software have been completed, and there may be inaccuracies that require secondary proofreading

简体中文：
软件内的所有翻译均已完成，可能有不准确的地方，需要二次校对

繁體中文：
應用程式内的所有文本已經翻譯，可能有錯誤的地方，需要再次校對

**Comment by OptimiliaStudios** [comment]
@taskmgrTZT 
I want to validate the localized build before official release, I'll release private bits to you for testing.
For that I would need the e-mail id you use to login to Microsoft Store. You can either share the email id here or send me at [optimilia.studios@gmail.com](mailto:optimilia.studios@gmail.com).
Thanks

**Comment by OptimiliaStudios** [comment]
@taskmgrTZT 
Request to plz reach out to us at optimilia.studios@gmail.com, we want to credit you for the translation efforts!

**Comment by taskmgrTZT** [comment]
@OptimiliaStudios 
I'm sorry.
I have sent an email to optimilia.studios@gmail.com on June 2nd, please check if it is classified as spam. I will also send another email to optimilia.studios@gmail.com after this message.

**Pull request merged**
